# Podfile

platform :ios, '13.0'
project 'RecipeList.xcodeproj'

use_frameworks!

target 'RecipeList' do
    pod 'RxSwift', '~> 6.5.0'
    pod 'RxCocoa', '~> 6.5.0'
    pod 'Moya', '~> 15.0.0'
    pod 'Moya/RxSwift'
    pod 'R.swift'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'RxDataSources'

end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'RecipeListTests' do
    pod 'RxBlocking', '~> 6.5.0'
    pod 'RxTest', '~> 6.5.0'
end

target 'RecipeListUITests' do
    pod 'RxBlocking', '~> 6.5.0'
    pod 'RxTest', '~> 6.5.0'
end



